export type CareerDnaStage = "DIRECTION" | "READING" | "RESEARCH" | "REFLECTION";

export interface CareerDnaQuestion {
  session: number;
  stage: CareerDnaStage;
  title: string;
  question: string;
  example: string;
  placeholder: string;
  rows: number;
}

export const CAREER_DNA_STAGE_LABELS: Record<CareerDnaStage, string> = {
  DIRECTION: "탐구 방향 설정",
  READING: "독서 기반 심화 탐구",
  RESEARCH: "융합 탐구",
  REFLECTION: "성장과 성찰",
};

export const CAREER_DNA_QUESTIONS: readonly CareerDnaQuestion[] = [
  {
    session: 1,
    stage: "DIRECTION",
    title: "확장 방향과 도달 목표",
    question: "1학년 활동을 바탕으로 올해 새롭게 확장하고 싶은 탐구 방향과 도달 목표를 적어 주세요. DNA를 처음 하거나 진로가 바뀌었다면 공백을 어떻게 보완하며 2학년 수준의 확장을 보여줄지도 포함해 주세요.",
    example: "1학년 때 배운 로봇 센서 지식을 바탕으로 실제 산업 현장의 협동 로봇 안전 규정과 효율성을 분석하고 싶다.",
    placeholder: "이전 활동 → 올해 확장할 내용 → 최종 도달 목표 순서로 작성해 보세요.",
    rows: 5,
  },
  {
    session: 2,
    stage: "DIRECTION",
    title: "전공·확장 키워드",
    question: "전공 키워드에 새롭게 결합할 확장 키워드를 포함하여 총 3가지 키워드와 선정 이유를 적어 주세요.",
    example: "로봇공학, 산업안전, 자동화 공정 — 인간 작업자와 안전하게 협업하기 위한 조건을 탐구하고 싶기 때문이다.",
    placeholder: "키워드 3개와 키워드 사이의 연결 이유를 작성해 주세요.",
    rows: 4,
  },
  {
    session: 3,
    stage: "READING",
    title: "도서 이론의 적용 계획",
    question: "선정한 도서의 핵심 이론을 실제 사회 현상이나 다른 학문에 어떻게 적용해 탐구할지 구체적인 연결 시나리오를 적어 주세요.",
    example: "로봇 팔 제어 원리를 바탕으로 스마트 팩토리의 사고 방지 시스템 도입 전후 사례를 비교한다.",
    placeholder: "책의 이론 → 적용 대상 → 조사·비교 방법을 연결해 작성해 주세요.",
    rows: 5,
  },
  {
    session: 4,
    stage: "READING",
    title: "도서 선정과 심화성",
    question: "도서 제목과 저자를 쓰고, 이전 독서보다 어떤 점에서 심화되거나 확장되었는지 적어 주세요.",
    example: "『협동 로봇 공학』(○○○)을 통해 인간과 로봇의 상호작용에 필요한 제어 이론과 안전 표준을 학습하고자 했다.",
    placeholder: "도서명 / 저자 / 이전 독서와의 차이 / 선정 이유를 작성해 주세요.",
    rows: 5,
  },
  {
    session: 5,
    stage: "READING",
    title: "핵심 이론과 활용 사례",
    question: "책의 핵심 이론이나 원리를 한 문장으로 요약하고 실제 분야에서의 활용 사례를 적어 주세요.",
    example: "힘 제어는 외부 저항을 감지해 동작을 수정하는 기술이며, 충돌 시 로봇을 멈추는 안전 장치에 활용된다.",
    placeholder: "핵심 원리와 실제 적용 사례를 구분해 작성해 주세요.",
    rows: 5,
  },
  {
    session: 6,
    stage: "READING",
    title: "비판적 검토",
    question: "저자의 주장 중 보완이 필요하거나 다른 연구와 상충한다고 판단한 내용을 근거와 함께 적어 주세요.",
    example: "완벽한 센서만으로 안전을 보장하기 어렵고 작업자 교육 같은 제도적 보완이 병행되어야 한다고 판단했다.",
    placeholder: "저자의 주장 → 의문점 또는 한계 → 나의 판단을 작성해 주세요.",
    rows: 5,
  },
  {
    session: 7,
    stage: "READING",
    title: "학문적 연결 고리",
    question: "책을 통해 발견한 학문적 연결 고리와 이 연결이 탐구를 어떻게 넓고 깊게 만들었는지 적어 주세요.",
    example: "로봇공학이 안전 규범 및 표준과 연결된다는 점을 발견해 탐구 범위를 기계 원리에서 산업 시스템 설계로 확장했다.",
    placeholder: "연결된 두 분야와 탐구 관점의 변화를 작성해 주세요.",
    rows: 5,
  },
  {
    session: 8,
    stage: "READING",
    title: "독서 탐구 발표 구성",
    question: "7장 이상 발표자료의 슬라이드 소제목을 순서대로 적고, 이전 활동과 비교해 강조할 차별화 포인트를 표시해 주세요.",
    example: "1. 이전 탐구 복기  2. 산업용 협동 로봇의 등장  3. 힘 제어 분석  4. 사고 유형 비교  5. 안전 가이드라인 제안  6. 시사점  7. 결론",
    placeholder: "1. …\n2. …\n3. … 형식으로 슬라이드 구성을 작성해 주세요.",
    rows: 8,
  },
  {
    session: 9,
    stage: "READING",
    title: "독서 탐구 발표 핵심 대사",
    question: "발표 영상에서 이전 활동과의 차별성과 이번 탐구의 핵심 연결 지점을 설명할 대사, 마무리 문장, 영상 링크를 적어 주세요.",
    example: "이전에는 센서가 장애물을 피하는 원리를 배웠다면, 올해는 로봇이 사람과 안전하게 일하기 위해 필요한 약속을 탐구했습니다.",
    placeholder: "핵심 멘트 / 마무리 / 발표 영상 URL을 작성해 주세요.",
    rows: 6,
  },
  {
    session: 10,
    stage: "RESEARCH",
    title: "융합 탐구 주제와 핵심 질문",
    question: "이번 학기에 깊이 탐구할 구체적인 융합 주제와 비교·분석 대상 및 방식을 적어 주세요.",
    example: "산업용 로봇과 협동 로봇의 안전 메커니즘을 비교하고 안전 거리와 사고 방지 효율의 관계를 살핀다.",
    placeholder: "주제 / 핵심 질문 / 비교 대상 / 분석 방법을 작성해 주세요.",
    rows: 5,
  },
  {
    session: 11,
    stage: "RESEARCH",
    title: "학문적 확장성과 목적",
    question: "이전 탐구와 비교한 학문적 확장성과 두 분야를 융합해 얻고자 하는 최종 목적을 적어 주세요.",
    example: "기술적 안전에서 실제 산업 시스템으로 관점을 넓혀 기술과 제도가 조화된 스마트 팩토리 모델을 구상한다.",
    placeholder: "이전 탐구 → 확장된 관점 → 융합의 최종 목적을 작성해 주세요.",
    rows: 5,
  },
  {
    session: 12,
    stage: "RESEARCH",
    title: "서로 다른 자료의 비교",
    question: "주제와 관련된 서로 다른 관점의 자료 2편 이상을 비교하고, 탐구의 핵심 근거가 될 통합적 이론을 적어 주세요.",
    example: "ISO 10218과 ISO/TS 15066을 비교해 안전 패러다임이 물리적 격리에서 공존으로 바뀌었음을 확인했다.",
    placeholder: "자료명·출처 / 각 관점 / 비교 결과 / 통합한 핵심 이론을 작성해 주세요.",
    rows: 6,
  },
  {
    session: 13,
    stage: "RESEARCH",
    title: "사례 3가지 비교",
    question: "탐구 주제를 검토할 서로 대조되는 실제 사례 3가지를 찾고 차이점과 공통점을 분석해 주세요.",
    example: "일반 로봇 공정, 협동 로봇 공정, 최신 스마트 팩토리를 비교해 인간의 돌발 행동과 작업 프로토콜의 중요성을 확인했다.",
    placeholder: "사례 1·2·3 / 공통점 / 차이점 / 사례가 보여주는 의미를 작성해 주세요.",
    rows: 7,
  },
  {
    session: 14,
    stage: "RESEARCH",
    title: "두 지식의 연결",
    question: "탐구를 뒷받침하는 핵심 이론을 바탕으로 서로 다른 두 지식이 어떻게 연결되는지 설명해 주세요.",
    example: "산업 안전의 물리적 격리 원칙과 로봇 제어의 속도·거리 감시 및 힘 제한 기술이 인간·로봇 공존 모델에서 연결된다.",
    placeholder: "지식 A / 지식 B / 연결 원리 / 탐구에서의 의미를 작성해 주세요.",
    rows: 7,
  },
  {
    session: 15,
    stage: "RESEARCH",
    title: "대조 사례의 문제점과 시사점",
    question: "두 가지 이상의 대조 사례를 비교하고, 차이에서 드러난 구체적인 문제점이나 시사점을 적어 주세요.",
    example: "일반 로봇은 규정 위반 시 중대 사고가, 협동 로봇은 잦은 비상 정지와 생산성 저하가 나타나 작업 프로토콜의 중요성이 드러났다.",
    placeholder: "대조 사례 / 관찰한 차이 / 원인 / 문제점 또는 시사점을 작성해 주세요.",
    rows: 7,
  },
  {
    session: 16,
    stage: "RESEARCH",
    title: "융합적 해결 대안",
    question: "분석한 문제를 해결하기 위해 기술+제도, 공학+심리처럼 두 관점 이상을 결합한 나만의 대안을 적어 주세요.",
    example: "동적 안전 구역 알고리즘과 인간 중심 작업 표준을 함께 도입하고, 작업자가 로봇의 다음 동작을 예측할 수 있게 한다.",
    placeholder: "해결할 문제 / 결합한 관점 / 구체적 작동 방식 / 기대 효과를 작성해 주세요.",
    rows: 7,
  },
  {
    session: 17,
    stage: "RESEARCH",
    title: "결론과 발전 방향",
    question: "융합 탐구의 핵심 결론, 학문적 통찰, 한계와 앞으로의 발전 방향을 적어 주세요.",
    example: "안전성은 감지 기술과 작업 표준의 융합에서 완성됨을 확인했고, 이후 디지털 트윈 시뮬레이션으로 대안을 검증하고 싶다.",
    placeholder: "결론 / 새롭게 얻은 통찰 / 탐구의 한계 / 후속 계획을 작성해 주세요.",
    rows: 7,
  },
  {
    session: 18,
    stage: "RESEARCH",
    title: "융합 탐구 발표 구성",
    question: "두 분야의 연결이 잘 드러나는 핵심 슬라이드 구성과 시각 자료 배치 계획, 발표 영상 링크를 적어 주세요.",
    example: "도입 → 두 분야의 연결 → 사고 메커니즘 비교표 → 직접 만든 가변 안전 모델 도식 → 탐구 확장 과정과 성찰",
    placeholder: "슬라이드 순서 / 사용할 표·그래프·도식 / 배치 이유 / 발표 영상 URL을 작성해 주세요.",
    rows: 8,
  },
  {
    session: 19,
    stage: "REFLECTION",
    title: "전문가로서의 성장",
    question: "이전의 기초 탐구와 올해의 융합 탐구가 나를 어떤 전문가로 성장시켰는지 구체적으로 정리해 주세요.",
    example: "하드웨어 중심 관점에서 실제 산업 시스템까지 시야를 넓혀 기술과 현장을 함께 이해하는 공학자로 성장했다.",
    placeholder: "처음의 관점 / 달라진 관점 / 구체적으로 성장한 점을 작성해 주세요.",
    rows: 6,
  },
  {
    session: 20,
    stage: "REFLECTION",
    title: "동료에게 받은 자극과 최종 피드백",
    question: "동료 발표에서 학문적 자극을 받은 점과 DNA 활동을 마친 자신에게 주는 최종 피드백을 적어 주세요.",
    example: "기술 도입을 경제적 비용 관점에서 분석한 발표를 통해 새로운 변수를 발견했고, 두 학문을 잇기 위해 자료를 찾은 끈기를 되돌아보았다.",
    placeholder: "친구의 발표에서 배운 점 / 내 탐구에 미친 영향 / 자신에게 주는 피드백을 작성해 주세요.",
    rows: 6,
  },
] as const;
